<?php

/**
 * Implements hook_permission().
 */
function google_remarketing_tag_permission() {
  return array(
    'administer google remarketing tag configuration' => array(
      'title' => t('Administer Google Remarketing Tag configuration'),
    )
  );
}

/**
 * Implements hook_theme().
 */
function google_remarketing_tag_theme($existing, $type, $theme, $path) {
  return array(
    'remarketing_tag' => array(
      'variables' => array(
        'conversion_id' => '',
        'conversion_label' => '',
        'custom_params' => '',
        'remarketing_only' => '',
      ),
      'path' => $path . '/templates',
      'template' => 'remarketing_tag',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function google_remarketing_tag_menu() {
  $items['admin/config/system/googleremarketingtag'] = array(
    'title' => 'Google Remarketing Tag Configuration',
    'description' => "Configure the settings used to integrate Google Remarketing Tag.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_remarketing_tag_admin_settings'),
    'access arguments' => array('administer google remarketing tag configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Admin settings form for module settings configuration.
 */
function google_remarketing_tag_admin_settings($form, &$form_state) {
  $form = array();

  $form['google_remarketing_tag_conversion_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Conversion ID'),
    '#default_value' => variable_get('google_remarketing_tag_conversion_id'),
    '#required' => TRUE,
  );

  $form['google_remarketing_tag_conversion_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Conversion Label'),
    '#default_value' => variable_get('google_remarketing_tag_conversion_label'),
    '#required' => FALSE,
  );

  $form['google_remarketing_tag_custom_params'] = array(
    '#type' => 'textfield',
    '#title' => t('Custom Params'),
    '#default_value' => variable_get('google_remarketing_tag_custom_params'),
    '#required' => FALSE,
  );

  $form['google_remarketing_tag_remarketing_only'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remarketing Only'),
    '#default_value' => variable_get('google_remarketing_tag_remarketing_only'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_page_alter().
 */
function google_remarketing_tag_page_alter(&$page) {
  if (path_is_admin(current_path())) {
    return;
  }

  $theme_vars = array();
  $theme_vars['conversion_id'] = variable_get('google_remarketing_tag_conversion_id', '');
  $theme_vars['custom_params'] = variable_get('google_remarketing_tag_custom_params', '');
  $tag_remarketing_only = variable_get('google_remarketing_tag_remarketing_only', '');
  $theme_vars['remarketing_only'] = empty($tag_remarketing_only) ? 'false' : 'true';
  $theme_vars['conversion_label'] = variable_get('google_remarketing_tag_conversion_label', '');

  $label = empty($theme_vars['conversion_label']) ? '' : 'label=' . $theme_vars['conversion_label'] . '&amp;';
  $theme_vars['src'] = '//googleads.g.doubleclick.net/pagead/viewthroughconversion/' . $theme_vars['conversion_id'] . '/?value=0&amp;' . $label . 'guid=ON&amp;script=0';

  if (!empty($theme_vars['conversion_id'])) {
    $page['page_bottom']['remarketing_tag'] = array(
      '#type' => 'markup',
      '#markup' => theme('remarketing_tag', $theme_vars),
    );
  }
}
